name = "remix-cloudflare-workers"
type = "javascript"

workers_dev = true

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"

[build.upload]
format="service-worker"

#[secrets]
#DATABASE_URL=""
